using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpawnerA : MonoBehaviour
{
	public List<Balls> ballList;
	
	
	void Start()
	{
		ballList = new List<Balls>();
	}
	
	
	void OnTriggerEnter2D(Collider2D col)
	{
		switch(col.gameObject.tag)
		{
			case "One":
			ballList.Add(new Balls { ballType = 16 }); 
			ballList.Add(new Balls { ballType = 80 }); 
			ballList.Add(new Balls { ballType = 88 });
			ballList.Add(new Balls { ballType = 36 }); 
			ballList.Add(new Balls { ballType = 70 }); 
			ballList.Add(new Balls { ballType = 1 }); 
			ballList.Add(new Balls { ballType = 47 }); 
			ballList.Add(new Balls { ballType = 59 }); 
			ballList.Add(new Balls { ballType = 80 }); 
			ballList.Add(new Balls { ballType = 64 }); 
			ballList.Add(new Balls { ballType = 69 });
			ballList.Add(new Balls { ballType = 57 }); 
			ballList.Add(new Balls { ballType = 15});
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 47});
			break;
			case "Two":
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 0});
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 84});
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 41});
			break;
			
			case "Three":
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 45});
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 55});
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 45}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 72});
			
			break;
			case "Four":
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 89}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 21});
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 53});
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 83}); 
			ballList.Add(new Balls { ballType = 74});
			break;
			case "Five":
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 35});
			ballList.Add(new Balls { ballType = 28}); 
			ballList.Add(new Balls { ballType = 78});
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 88}); 
			ballList.Add(new Balls { ballType = 23});
			break;
			case "Six":
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 88});
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 61});
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 85}); 
			break;
			case "Seven":
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 3});
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 37});
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 37});
			break;
			case "Eight":
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 27}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 62});
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 16});
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 27}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 7});
			break;
			case "Nine":
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 27}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 33});
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 66});
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 83}); 
			break;
			case "Ten":
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 58}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 16});
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 58});
			ballList.Add(new Balls { ballType = 45}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 31});
			break;
			case "Eleven":
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 46});
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 64});
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 89}); 
			ballList.Add(new Balls { ballType = 26});
			break;
			case "Twelve":
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 4});
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 42});
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 38});
			break;
			case "Thirteen":
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 31});
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 21});
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 6});
			break;
			case "Fourteen":
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 19});
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 22});
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 44});
			break;
			case "Fifteen":
			ballList.Add(new Balls { ballType = 28}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 88}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 20}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 18});
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 78});
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 80});
			break;
			case "Sixteen":
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 71}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 20});
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 53});
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 42});
			break;
			case "Seventeen":
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 88}); 
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 12});
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 8});
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 13});
			break;
			case "Eighteen":
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 54}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 41}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 18});
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 46});
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 75});
			break;
			case "Nineteen":
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 8});
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 34});
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 50});
			break;
			case "Twenty":
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 71}); 
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 56});
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 67});
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 37});
			break;
			case "TwentyOne":
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 81});
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 16});
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 32});
			break;
			case "TwentyTwo":
			ballList.Add(new Balls { ballType = 71}); 
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 28}); 
			ballList.Add(new Balls { ballType = 54}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 79}); 
			ballList.Add(new Balls { ballType = 41}); 
			ballList.Add(new Balls { ballType = 71});
			ballList.Add(new Balls { ballType = 79}); 
			ballList.Add(new Balls { ballType = 82});
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 87});
			break;
			case "TwentyThree":
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 0});
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 29});
			ballList.Add(new Balls { ballType = 20}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 69});
			break;
			case "TwentyFour":
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 20}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 11});
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 86});
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 74});
			break;
			case "TwentyFive":
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 89}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 16});
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 27});
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 6});
			break;
			case "TwentySix":
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 66});
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 54});
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 39});
			
			break;
			case "TwentySeven":
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 40});
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 79});
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 58});
			
			break;
			case "TwentyEight":
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 85});
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 69});
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 84});
			break;
			case "TwentyNine":
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 71});
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 14});
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 35});
			
			break;
			case "Thirty":
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 58}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 1});
			ballList.Add(new Balls { ballType = 20}); 
			ballList.Add(new Balls { ballType = 72});
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 68});
			
			break;
			case "ThirtyOne":
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 28});
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 88});
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 9});
			
			break;
			case "ThirtyTwo":
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 71});
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 23});
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 16}); 
			
			break;
			case "ThirtyThree":
			ballList.Add(new Balls { ballType = 45}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 70});
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 73});
			ballList.Add(new Balls { ballType = 88}); 
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 65});
			
			break;
			case "ThirtyFour":
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 64});
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 62});
			ballList.Add(new Balls { ballType = 20}); 
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 86});
			
			break;
			case "ThirtyFive":
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 40});
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 73});
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 59});
			
			break;
			case "ThirtySix":
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 71}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 33});
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 67});
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 78});
			
			break;
			case "ThirtySeven":
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 5});
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 15});
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 33});
			
			break;
			case "ThirtyEight":
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 88}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 63});
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 56});
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 20});
			
			break;
			case "ThirtyNine":
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 25});
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 11});
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 10});
			
			break;
			case "Fourty":
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 83}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 47});
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 10});
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 17});
			
			break;
			case "FourtyOne":
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 31});
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 64});
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 43});
			
			break;
			case "FourtyTwo":
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 79}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 58}); 
			ballList.Add(new Balls { ballType = 54});
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 3});
			ballList.Add(new Balls { ballType = 79}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 8});
			
			break;
			case "FourtyThree":
			ballList.Add(new Balls { ballType = 88}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 14});
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 80});
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 70});
			
			break;
			case "FourtyFour":
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 57});
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 10});
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 20}); 
			ballList.Add(new Balls { ballType = 48});
			
			break;
			case "FourtyFive":
			ballList.Add(new Balls { ballType = 20}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 12});
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 72});
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 25});
			
			break;
			case "FourtySix":
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 66});
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 74});
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 58}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 55});
			
			break;
			case "FourtySeven":
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 52});
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 33});
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 29});
			
			break;
			case "FourtyEight":
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 41}); 
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 39});
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 70});
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 67});
			
			break;
			case "FourtyNine":
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 43});
			ballList.Add(new Balls { ballType = 58}); 
			ballList.Add(new Balls { ballType = 17});
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 19});
			
			break;
			case "Fifty":
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 58}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 27}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 45});
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 38});
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 82});
			 
			break;
			case "FiftyOne":
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 85});
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 75});
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 59});
			
			break;
			case "FiftyTwo":
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 88}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 27}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 85});
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 4});
			ballList.Add(new Balls { ballType = 58}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 3});
			
			break;
			case "FiftyThree":
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 83}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 77});
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 88});
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 33});
			
			break;
			case "FiftyFour":
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 44});
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 79});
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 63});
			
			break;	
			case "FiftyFive":
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 65});
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 0});
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 1});
			
			break;
			case "FiftySix":
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 45}); 
			ballList.Add(new Balls { ballType = 43});
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 20});
			ballList.Add(new Balls { ballType = 71}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 55});
			
			break;
			case "FiftySeven":
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 58}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 58}); 
			ballList.Add(new Balls { ballType = 45}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 40});
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 20});
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 67});
			
			break;
			case "FiftyEight":
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 44});
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 57});
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 43});
			
			break;
			case "FiftyNine":
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 71}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 83}); 
			ballList.Add(new Balls { ballType = 38});
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 39});
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 21});
			
			break;
			case "Sixty":
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 49});
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 44});
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 71});
			
			break;
			case "SixtyOne":
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 32});
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 14});
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 26});
			
			break;
			case "SixtyTwo":
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 28}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 27}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 22});
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 30});
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 83}); 
			ballList.Add(new Balls { ballType = 75});
			
			break;
			case "SixtyThree":
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 1});
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 49});
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 29});
			
			break;
			case "SixtyFour":
			ballList.Add(new Balls { ballType = 45}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 54}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 82}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 59});
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 13});
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 55});
			
			break;
			case "SixtyFive":
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 89}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 71}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 13});
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 28});
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 83}); 
			ballList.Add(new Balls { ballType = 58});
			
			break;
			case "SixtySix":
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 85}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 57});
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 52});
			ballList.Add(new Balls { ballType = 83}); 
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 56});
			
			break;
			case "SixtySeven":
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 28}); 
			ballList.Add(new Balls { ballType = 40});
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 24});
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 44});
			
			break;
			case "SixtyEight":
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 28}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 29});
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 24});
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 77});
			
			break;
			case "SixtyNine":
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 51});
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 3});
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 32});
			 
			break;
			case "Seventy":
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 82});
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 39});
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 65}); 
			ballList.Add(new Balls { ballType = 14});
			
			break;
			case "SeventyOne":
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 71}); 
			ballList.Add(new Balls { ballType = 88}); 
			ballList.Add(new Balls { ballType = 64}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 61});
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 5});
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 64});
			 
			break;
			case "SeventyTwo":
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 4}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 68});
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 76});
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 33});
			
			break;
			case "SeventyThree":
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 79}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 23});
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 2});
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 69});
			 
			break;
			case "SeventyFour":
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 79}); 
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 89}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 39}); 
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 78});
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 73});
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 14});
			
			break;
			case "SeventyFive":
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 28}); 
			ballList.Add(new Balls { ballType = 23});
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 4});
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 39});
			
			break;
			case "SeventySix":
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 84}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 69}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 45}); 
			ballList.Add(new Balls { ballType = 47});
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 38});
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 80});
			
			break;
			case "SeventySeven":
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 88}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 16});
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 88});
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 22});
			
			break;
			case "SeventyEight":
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 79}); 
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 76}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 73});
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 49});
			ballList.Add(new Balls { ballType = 27}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 0});
			
			break;
			case "SeventyNine":
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 27}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 55});
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 68});
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 76});
			 
			break;
			case "Eighty":
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 17}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 60});
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 65});
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 54}); 
			ballList.Add(new Balls { ballType = 3}); 
			ballList.Add(new Balls { ballType = 15});
			
			break;
			case "EightyOne":
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 89}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 48}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 65});
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 0});
			ballList.Add(new Balls { ballType = 38}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 83});
			
			break;
			case "EightyTwo":
			ballList.Add(new Balls { ballType = 45}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 55}); 
			ballList.Add(new Balls { ballType = 63}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 71}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 57});
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 42});
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 66}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 73});
			
			break;
			case "EightyThree":
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 68}); 
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 70});
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 57});
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 28}); 
			ballList.Add(new Balls { ballType = 62});
			
			break;
			case "EightyFour":
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 77}); 
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 67}); 
			ballList.Add(new Balls { ballType = 22}); 
			ballList.Add(new Balls { ballType = 0}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 25}); 
			ballList.Add(new Balls { ballType = 14});
			ballList.Add(new Balls { ballType = 86}); 
			ballList.Add(new Balls { ballType = 83});
			ballList.Add(new Balls { ballType = 24}); 
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 87}); 
			ballList.Add(new Balls { ballType = 53});
			
			break;
			case "EightyFive":
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 49});
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 31});
			ballList.Add(new Balls { ballType = 33}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 1}); 
			ballList.Add(new Balls { ballType = 83}); 
			ballList.Add(new Balls { ballType = 57});
			
			break;
			case "EightySix":
			ballList.Add(new Balls { ballType = 57}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 52}); 
			ballList.Add(new Balls { ballType = 83}); 
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 8}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 47}); 
			ballList.Add(new Balls { ballType = 19}); 
			ballList.Add(new Balls { ballType = 37});
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 70});
			ballList.Add(new Balls { ballType = 32}); 
			ballList.Add(new Balls { ballType = 72}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 68});
			
			break;
			case "EightySeven":
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 12}); 
			ballList.Add(new Balls { ballType = 10}); 
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 40}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 35}); 
			ballList.Add(new Balls { ballType = 70}); 
			ballList.Add(new Balls { ballType = 77});
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 12});
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 13}); 
			ballList.Add(new Balls { ballType = 89}); 
			ballList.Add(new Balls { ballType = 48});
			
			break;
			case "EightyEight":
			ballList.Add(new Balls { ballType = 74}); 
			ballList.Add(new Balls { ballType = 89}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 49}); 
			ballList.Add(new Balls { ballType = 27}); 
			ballList.Add(new Balls { ballType = 56}); 
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 53}); 
			ballList.Add(new Balls { ballType = 44}); 
			ballList.Add(new Balls { ballType = 2}); 
			ballList.Add(new Balls { ballType = 40});
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 66});
			ballList.Add(new Balls { ballType = 30}); 
			ballList.Add(new Balls { ballType = 23}); 
			ballList.Add(new Balls { ballType = 51}); 
			ballList.Add(new Balls { ballType = 80}); 
			ballList.Add(new Balls { ballType = 79});
			
			break;
			case "EightyNine":
			ballList.Add(new Balls { ballType = 46}); 
			ballList.Add(new Balls { ballType = 9}); 
			ballList.Add(new Balls { ballType = 75}); 
			ballList.Add(new Balls { ballType = 61}); 
			ballList.Add(new Balls { ballType = 11}); 
			ballList.Add(new Balls { ballType = 29}); 
			ballList.Add(new Balls { ballType = 59}); 
			ballList.Add(new Balls { ballType = 26}); 
			ballList.Add(new Balls { ballType = 60}); 
			ballList.Add(new Balls { ballType = 43}); 
			ballList.Add(new Balls { ballType = 89});
			ballList.Add(new Balls { ballType = 6}); 
			ballList.Add(new Balls { ballType = 39});
			ballList.Add(new Balls { ballType = 42}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 34}); 
			ballList.Add(new Balls { ballType = 50}); 
			ballList.Add(new Balls { ballType = 77});
			
			break;
			case "Ninety":
			ballList.Add(new Balls { ballType = 62}); 
			ballList.Add(new Balls { ballType = 73}); 
			ballList.Add(new Balls { ballType = 37}); 
			ballList.Add(new Balls { ballType = 21}); 
			ballList.Add(new Balls { ballType = 18}); 
			ballList.Add(new Balls { ballType = 16}); 
			ballList.Add(new Balls { ballType = 5}); 
			ballList.Add(new Balls { ballType = 45}); 
			ballList.Add(new Balls { ballType = 15}); 
			ballList.Add(new Balls { ballType = 7}); 
			ballList.Add(new Balls { ballType = 5});
			ballList.Add(new Balls { ballType = 78}); 
			ballList.Add(new Balls { ballType = 11});
			ballList.Add(new Balls { ballType = 31}); 
			ballList.Add(new Balls { ballType = 14}); 
			ballList.Add(new Balls { ballType = 81}); 
			ballList.Add(new Balls { ballType = 36}); 
			ballList.Add(new Balls { ballType = 54});
			 
			
			break;
			
			
			
		}
		
	}
	
}